import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { Providers } from "./providers";
import { Rubik } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Factoou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <Providers>
          <NextTopLoader
            color="#FFFF00"
            height={3}
            easing="ease"
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            zIndex={1600}
          />
          <Header />
          <div className="mt-32 max-w-7xl xl:max-w-6xl mx-auto px-10">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
